Add WithRandomColor to EmbedBuilderExtensions
Rozen4334/Discord.Net.Extensions pull request #17
Opened 2022-05-16 18:17 UTC by Tesseract-arch

2022-05-16 18:42 UTC, Rozen4334 requested changes
Consider making the Random lazy so it doesn't get initialized until called.

2022-05-16 18:42 UTC, Rozen4334 commented on Discord.Net.Extensions/Core/Embeds/EmbedBuilderExtensions.cs
> +        private static readonly Random random = new();
```suggestion
        private static readonly Lazy<Random> _random = new(() => new());
```

2022-05-16 18:42 UTC, Rozen4334 commented on Discord.Net.Extensions/Core/Embeds/EmbedBuilderExtensions.cs
> +        public static EmbedBuilder WithRandomColor(this EmbedBuilder builder) => builder.WithColor(new Color((uint)random.Next(0xFFFFFF)));
```suggestion
        public static EmbedBuilder WithRandomColor(this EmbedBuilder builder) => builder.WithColor(new Color((uint)_random.Value.Next(0xFFFFFF)));
```

2022-05-17 05:07 UTC, Tesseract-arch commented
> Consider making the Random lazy so it doesn't get initialized until called.

Good idea, updated.

2022-05-17 13:48 UTC, merged